name: Deploy via VPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deployment  # 👈 Specify the GitHub Environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn

      - name: Configure VPN
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > vpn.ovpn
          echo -e "${{ secrets.VPN_USERNAME }}\n${{ secrets.VPN_PASSWORD }}" > vpn-auth.txt
          chmod 600 vpn-auth.txt
          sed -i 's/^auth-user-pass$/auth-user-pass vpn-auth.txt/' vpn.ovpn
          sudo openvpn --config vpn.ovpn --daemon
          sleep 10  # Wait for connection
        
      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.1.4 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh lucas@192.168.1.4 "cd /var/www/SMKID-overview && git pull origin main && npm install && npm run build"

      - name: Cleanup VPN
        if: always()
        run: |
          sudo pkill openvpn
